# Note: This is a configuration of the ChatControl plugin
# Official page: http://www.spigotmc.org/resources/chatcontrol.271/
# SLOVAK DEVELOPER FTW
# Supports color codes: & + 0 - F

Chat:
  Block_Duplicate_Messages: true
  # Block 75% similar messages.
  Block_Similar_Messages: true
  # When blocking duplicate message, should we strip UTF-8 special characters from it?
  # e.g messages "Hello" and "<<Hello!?!" will after this strip be detected as equals.
  # Which can lower spam and preventing users bypassing this check by adding some characters like ! ? etc.
  Strip_Unicode: true
  Message_Delay: 1
  Write_To_File: true
  Ignore_Players:
    - anonymouser1
  # Commands that get writed along with the chat messages.
  Include_Commands:
    - /tell
    - /msg
    - /r

Messages:
  # Default - not handled by ChatControl; none - message will not shown. Or just write your own message .
  # Example: Join_Message: "&e&o%player &6just quit the game"
  # Variables: %player and %prefix
  Common:
    Join_Message: default
    Quit_Message: default
    Kick_Message: default

Grammar:
  Capitalize: 
    Enabled: true
    Minimum_Msg_Length: 5
  Insert_Dot: 
    Enabled: false
    Minimum_Msg_Length: 5

Commands:
  Block_Duplicate_Commands: false
  Block_Similar_Messages: false      # New in 4.4.1
  Strip_Unicode: true                 # New in 4.4.1
  Command_Delay: 1
  Whitelist_Time:
    - tell
  Whitelist_Duplication:
    - tpa
    - spawn
    - home

Protect:
  Prevent_Tab_Complete: false

Signs:
  Advertising_Check: true
  # If false, plugin just disallow the text.
  Rewrite_Lines: true
  Rewrite_Text: "Advertising was:&4detected.:Please do not:advertise."
  # Check for signs text duplication. Fair players can get annoyed, deal with caution.
  Duplication_Check: false

Mute:
  Broadcast: true
  Disable:
    Join_Messages: true
    Quit_Messages: true
    Kick_Messages: true
    Death_Messages: true
  Disabled_Commands_During_Mute:
    - me
    
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: false
  Amount_Of_Lines_To_Clear_In_Console: 300

Anti_Bot:
  Rejoin_Time: 4

Anti_Caps:
  Enabled: true
  Minimum_Message_Length: 5
  Total_Caps_Percentage: 50
  Caps_In_A_Row: 5
  Warn_Player: true
  Whitelist:
    - OMG
    - LOL
    - ROFL

Anti_Swear:
  Enabled: true
  Enabled_In_Commands: false
  Command_Whitelist:
    - /register
    - /reg
    - /login
    - /l
  Block_Message: false
  Warn_Player: true
  Inform_Admins: true
  Replace_Word: true
  # Note: This fully works only on regex expressions.
  Replacement: "****"
  # Use %player for player and %message for message.
  Custom_Command: none
  # Careful with Regular Expressions. Can broke the plugin!
  Word_List:
    - \bf(u|v)(c)(k|q)|\bf'ing|\bf(c)k\b
    - b(i|1|!)tch
    - \bpiss off
    - \bsuck
    - \bass\b
    - n(o)(o|0|00)b
    - l(o|0)(o)s(e|3)r
    - ".*p+u+s+s+(y|ies|y+s).*"

Anti_Ad:
  Enabled: true
  Enabled_In_Commands: true
  Command_Whitelist:
    - /register
    - /reg
    - /login
    - /l
    - /auction
    - //                   # Ignore WorldEdit.
  Inform_Admins: true
  Console_Message: true
  Broadcast: true
  Write_To_File: true
  # Filter based on RegEx improves the standard filters below. It replaces characters [,],(,) by default.
  Filter_Pre_Process: "[(\\[\\])]"
  # Careful with the Regular Expressions. Random changing might blow of your server!
  IP_Filter: "\\b[0-9]{1,3}(\\.|dot|-|;|:|,|(\\W|\\d|_)*\\s)+[0-9]{1,3}(\\.|dot|-|;|:|,|(\\W|\\d|_)*\\s)+[0-9]{1,3}(\\.|dot|-|;|:|,|(\\W|\\d|_)*\\s)+[0-9]{1,3}\\b"
  Domain_Filter: "[a-zA-Z0-9\\-\\.]+\\s?(\\.|dot|\\(dot\\)|-|;|:|,)\\s?(com|org|net|mil|cz|co|uk|sk|cc|ws|ca|biz|mobi|xxx|tv|eu)\\b"
  Custom_Filter: none
  Custom_Command: none
  Whitelisted:
    IP:
      - 0.0.0.0
      - 127.0.0.1
    Domains:
      - youtube.com
      - google.com

Miscellaneous:
  Minimum_Players_To_Enable_Plugin: 2
  Block_Chat_Until_Moved: true
  Op_Has_Permissions: true
  Automatically_Update_Config: true
  Check_For_Updates: true
  Download_Automatically: true
  Notify_New_Version: true
  Debug: false

Localization:
  # Use %prefix to add the prefix.
  Dupe_Message: "&cPlease do not repeat the same (or similar) message."
  Dupe_Command: "&cPlease do not repeat the same (or similar) command."
  Dupe_Sign: "&cPlease do not repeat the same text on sign."
  Time_Message: "&cPlease wait %time second(s) before next message."
  Command_Message: "&cPlease wait %time second(s) before next command."
  
  Ad_Message: "&7Please do not advertise other websites or IP adresses."
  Ad_Staff_Message: "&c%player possibly advertises: &f%message "
  Ad_Broadcast_Message: "&c%player possibly advertises!"
  Ad_Console_Message: "&c%player possibly advertises: &f%message"
  
  Caps_Message: "&cDo not use so much CAPS LOCK"
  
  Successful_Mute: "&7Chat was successfully muted."
  Successful_Unmute: "&7The chat is now unmuted."
  
  Broadcast_Mute: "%prefix &eChat was muted by %player!"
  Broadcast_Silent_Mute: "&cInitiated global chat mute."
  
  Broadcast_Unmute: "%prefix &eChat was unmuted by %player!"  
  Broadcast_Silent_Unmute: "&cGlobal chat mute was cancelled."
  
  Broadcast_Clear: "%prefix &eChat was cleared by %player!"
  Broadcast_Silent_Clear: "&cThe game chat was cleared."
  
  Successful_Console_Clear: "%prefix &7Console was successfuly cleared."
  Do_Not_Swear: "&cPlease do not swear!"
  Swear_Admin_Message: "&c%player swears:&f %message"
  
  Cannot_Chat_While_Muted: "&7You cannot chat while the chat is muted."
  Cannot_Command_While_Muted: "&7You cannot use this command while the chat is muted."
  Cannot_Chat_Until_Moved: "&7You cannot chat until you move."
  Cannot_Broadcast_Empty_Message: "&cMessage at %event is none, therefore nothing is broadcasted."
  
  Staff_Chat_Clear_Message: "&7^----- [ == &fChat was cleared by %player &7== ] -----^"
  Rejoin_Message: "&6Please wait &7%time second(s)&6 before logging in."
  Update_Needed: "&2A new version of &3ChatControl&2 is available.\n&2Current version: &f%current&2; New version: &f%new\n&2You can disable this notification in its config."
  Reload_Complete: "&7Plugin was reloaded successfully."
  No_Permission: "&cYou do not have permission for this."
  
  Wrong_Args: "&cWrong arguments. Type &6/chc list&c for command list."
  Wrong_Parameters: "&cWrong parameters, available are: &7%params"
  
  Usage_Fake_Cmd: "%prefix Usage: /chatcontrol fake <&bjoin&f/&aleave&f>"
  
  Reason: "&7Reason:&f%reason"
  Prefix: "&8[&3ChatControl&8]&f"
  Console: "&4server"

Do_Not_Change_Version_Number: 4.4.5
