name: ChatControl
main: chatcontrol.ChatControl
version: 4.4.6-SNAPSHOT
author: kangarko
soft-depend: [ProtocolLib]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatfilter, filter]
    description: Main ChatControl command. Type /chatcontrol list for commands.
